name: instagram_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  cloud_firestore: 3.4.3
  firebase_storage: 10.3.4
  firebase_core: 1.20.0
  firebase_auth: 3.6.2
  image_picker: 0.8.5+3
  uuid: 3.0.6
  intl: 0.17.0
  flutter_staggered_grid_view: 0.6.2
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/
  uses-material-design: true

